HotelTelegramBot::Controller::Validator
readonly string HotelTelegramBot.Controller.Validator.BadDateFormat
readonly string HotelTelegramBot.Controller.Validator.BadDateLessCurrent
readonly string HotelTelegramBot.Controller.Validator.BadDateRange
readonly string HotelTelegramBot.Controller.Validator.BadNumber
readonly string HotelTelegramBot.Controller.Validator.BadNumberRange
readonly string HotelTelegramBot.Controller.Validator.BadEmail
readonly string HotelTelegramBot.Controller.Validator.BadPhoneNumber
readonly string HotelTelegramBot.Controller.Validator.BadName
static bool HotelTelegramBot.Controller.Validator.CheckDateFormat(string userDate)
Referenced by HotelTelegramBot.Controller.BookRoom_00.ReceiveMessageAsync, HotelTelegramBot.Controller.BookRoom_01.ReceiveMessageAsync.
static bool HotelTelegramBot.Controller.Validator.CheckDateBigerCurrent(string userDate)
Referenced by HotelTelegramBot.Controller.BookRoom_00.ReceiveMessageAsync, HotelTelegramBot.Controller.BookRoom_01.ReceiveMessageAsync.
static bool HotelTelegramBot.Controller.Validator.CheckDateRange(string start, string end)
Referenced by HotelTelegramBot.Controller.BookRoom_01.ReceiveMessageAsync.
static bool HotelTelegramBot.Controller.Validator.CheckNumber(string userNumber)
Referenced by HotelTelegramBot.Controller.BookRoom_02.ReceiveMessageAsync, HotelTelegramBot.Controller.BookRoom_03.ReceiveMessageAsync, HotelTelegramBot.Controller.HotelRoom_0.ReceiveMessageAsync, HotelTelegramBot.Controller.BookRoom_04.ReceiveMessageAsync.
static bool HotelTelegramBot.Controller.Validator.CheckNumberRange(string userNumber)
Referenced by HotelTelegramBot.Controller.BookRoom_02.ReceiveMessageAsync, HotelTelegramBot.Controller.BookRoom_03.ReceiveMessageAsync.
static bool HotelTelegramBot.Controller.Validator.CheckEmail(string userEmail)
Referenced by HotelTelegramBot.Controller.BookRoom_09.ReceiveMessageAsync.
static bool HotelTelegramBot.Controller.Validator.CheckPhoneNumber(string number)
Referenced by HotelTelegramBot.Controller.BookRoom_08.ReceiveMessageAsync.
static bool HotelTelegramBot.Controller.Validator.CheckName(string name)
Referenced by HotelTelegramBot.Controller.BookRoom_07.ReceiveMessageAsync, HotelTelegramBot.Controller.BookRoom_05.ReceiveMessageAsync, HotelTelegramBot.Controller.BookRoom_06.ReceiveMessageAsync.